version: '3.8'

services:
  db:
    image: postgres:15
    container_name: books_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-maneki_kakutasu}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-books_base}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app_container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_USER=${DB_USER:-maneki_kakutasu}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-books_base}
    depends_on:
      - db

volumes:
  postgres_data: